### ISSUE TITLE
running syntacts on linux background

### ISSUE THREAD

**Issue by zkarach1** [mahilab/Syntacts#4]
Hi
I am having some trouble running syntacts in ubuntu with a linux background. I follow the steps in this link https://www.syntacts.org/tutorials/building/ and am able to run all the commands except for the final one : 
sudo cmake --build . --target install

I get the follow error when I run the above command: 
![Screenshot from 2021-07-14 16-04-54](https://user-images.githubusercontent.com/60860244/125685745-6bedaab5-fb8f-4511-ae53-310c9021e167.png)

**Comment by zkarach1** [comment]
Im trying to generate the library i need for linux to run scripts like the example.py but cannot until i have the library for linux.

Thank you!

**Comment by gadzooks00** [comment]
@zkarach1, thank you for your question. Your error is being caused by your choice of C++ compiler. The std filesystem library is not implemented by all compilers. While we haven't done extensive testing of Syntacts on Linux systems, Clang and GNU C++ compilers should work. Please reference our tutorial page here:
[https://www.syntacts.org/tutorials/building/](https://www.syntacts.org/tutorials/building/)

**Comment by epezent** [comment]
@gadzooks00 , this may require some changes to Syntacts in [Library.cpp](https://github.com/mahilab/Syntacts/blob/master/src/Tact/Library.cpp). Some compilers still implement the feature in `<experimental/filesystem>`. A simple macro wrapper would probably do the trick:

https://stackoverflow.com/questions/53365538/how-to-determine-whether-to-use-filesystem-or-experimental-filesystem

**Comment by epezent** [comment]
@zkarach1 , the more information you share about your compiler, OS, and build environment, the better we can assist you.

**Comment by zkarach1** [comment]
> @zkarach1 , the more information you share about your compiler, OS, and build environment, the better we can assist you.

hi so these r the compiler available on my computer
![Screenshot from 2021-07-29 18-49-46](https://user-images.githubusercontent.com/60860244/127575300-0a5f751e-5301-456a-97e5-bdd8c2660ca4.png)

OS :+1: Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial

**Comment by zkarach1** [comment]
Hi so 

> @zkarach1, thank you for your question. Your error is being caused by your choice of C++ compiler. The std filesystem library is not implemented by all compilers. While we haven't done extensive testing of Syntacts on Linux systems, Clang and GNU C++ compilers should work. Please reference our tutorial page here:
> https://www.syntacts.org/tutorials/building/

hi so I am running with clang and I adjusted the Library.cpp file to have #include <experimental/filesystem> and namespace fs = std::experimental::filesystem;
so that file runs now but now I am getting this error within the session.cpp file i tried to make the changed in the error comments but its still not working there are more errors
![Screenshot from 2021-08-02 15-57-54](https://user-images.githubusercontent.com/60860244/127916569-428449ca-5f39-4608-9ba4-0bce51dced68.png)

**Comment by gadzooks00** [comment]
@zkarach1 
I have just merged an updated wrapper for filesystem to the Syntacts main branch. Please sync and attempt a fresh build.

**Comment by zkarach1** [comment]
> @zkarach1
> I have just merged an updated wrapper for filesystem to the Syntacts main branch. Please sync and attempt a fresh build.

hi thanks so much! the Libary.cpp file works but now I still get the error in the Session.cpp file as shown above
![Screenshot from 2021-08-02 16-25-39](https://user-images.githubusercontent.com/60860244/127919461-ff2f7da2-a02b-4613-bd7c-022b727ba333.png)

**Comment by epezent** [comment]
Enable C++17 features on your compiler for `if constexpr`

**Comment by gadzooks00** [comment]
@zkarach1 Has that resolved your issue?

**Comment by zkarach1** [comment]
> @zkarach1 Has that resolved your issue?

Hi so right now I was able to build in Linux after updating everything. I had to update my Ubuntu to a newer version. However now even though I can run the scripts I am not getting any outputs. For example I run the example.devices.py file but get no outputs. So I went into the Syntact.py file and looked in the Session class and the n variable is always being assigned to 0, which I am guessing is because the python script is not able to find any devices? I try running other files like example_basic.py and though they run there is no output. Like there are no errors but a signal is not outputted. 

I tried running this on windows and everything works so I am guessing there is something I need to change for windows? 

Please let me know!

**Comment by zkarach1** [comment]
Hi just updated it with a new question about trying to output a signal

**Comment by zkarach1** [comment]
Here is what happens when I try to run example_devices.py. I have attached a picture of the code, how I am compiling it in the terminal and the output (which is nothing) 
![Screenshot from 2021-08-23 14-28-49](https://user-images.githubusercontent.com/60860244/130498391-72589468-15ec-45ee-86fa-5391828fe2ea.png)
![Screenshot from 2021-08-23 14-28-59](https://user-images.githubusercontent.com/60860244/130498401-5970eedf-a341-4c0d-afeb-524d410c95c4.png)

I also tried example_basic.py and tried connecting the output device using session.open(api=API.ALSA) and session.open()I have attached my code. But I am not getting any ouptut. The code runs but there is no output sound. 
![Screenshot from 2021-08-23 14-33-49](https://user-images.githubusercontent.com/60860244/130499360-d1fc0cba-31d1-49ad-b3dc-86e0d287b878.png)
![Screenshot from 2021-08-23 14-34-02](https://user-images.githubusercontent.com/60860244/130499370-f2caa9dc-37e2-4789-873b-cd4849aa520f.png)
![Screenshot from 2021-08-23 14-34-09](https://user-images.githubusercontent.com/60860244/130499375-30701098-6d84-41dc-b320-4bf10913443e.png)

I think my problem is connecting to an output device. I used python -m sounddevice to check what devices I have and this is the output. So I think i need to use the ALSA api but that didnt work (as shown above) 
![Screenshot from 2021-08-23 14-37-17](https://user-images.githubusercontent.com/60860244/130499772-6e6eb43a-af4d-4e71-8361-ef08abfb2fd2.png)

Please let me know if you have any suggestions!!

**Comment by zkarach1** [comment]
RUNNING THE MYAPP:

Hi so for the first thing I did is get syntacts from github and I did that and have the folder on my computer. 
The second thing I tried to do was follow the c++ tutorial to set up the c++ API. From my understanding I need to do this outside of the Syntacts folder I have ?  My current set up is that in my home directory I have the Syntacts folder and another folder (not inside the Syntacts folder but made in my home directory) to build the c++ API in (I have named this c_test for reference). So inside of my new folder c_test I follow the c++ API tutorial instructions in order to generate the myApp executable. 
I do the following commands inside the c_test folder which contains both my CMakeList.txt and my  main.cpp file:
mkdir build
cd build
cmake ..
cmake --build . --config Release

and then to run the myApp I just do the command ./myApp

And I have a vibration output on my speakers that are connected to the mahi amplifier but I also have this error: 

![Screenshot from 2021-08-30 15-04-26](https://user-images.githubusercontent.com/60860244/131391362-7c542c68-0b1c-498a-91f9-58c633de20ee.png)
![Screenshot from 2021-08-30 15-04-39](https://user-images.githubusercontent.com/60860244/131391368-e4b0d30c-5c93-43c8-82d7-1cbe950a143b.png)
![Screenshot from 2021-08-30 15-04-48](https://user-images.githubusercontent.com/60860244/131391373-e1e42ff7-4605-4a37-9d17-9c6f38e3ceb1.png)

**Comment by zkarach1** [comment]
RUNNING A C++ FILE:

So from my understanding if I am trying to run a c++ file I need to run it in the c++ API build folder that I generated above ^
so I want to run the example_devices.cpp file I had shown above. So What I did was I added that file to the c_test folder which is where I built the c++ API and then just added it to the CMakelist.txt file like this: 

![Screenshot from 2021-08-30 15-14-51](https://user-images.githubusercontent.com/60860244/131392592-b175958d-d126-4d67-ac64-ee7a8cc3cbfd.png)

which worked! and I get device names, but I also have warnings I have attached the output below
![Screenshot from 2021-08-30 15-17-27](https://user-images.githubusercontent.com/60860244/131392877-afdde208-5d0d-49d3-9abd-7204798e396a.png)
![Screenshot from 2021-08-30 15-17-40](https://user-images.githubusercontent.com/60860244/131392888-a5661425-a094-4180-b529-d3f9e92c074f.png)
![Screenshot from 2021-08-30 15-17-48](https://user-images.githubusercontent.com/60860244/131392896-ee6e4d97-5b31-4011-bbe9-a11dd382e48d.png)
:

**Comment by zkarach1** [comment]
OPENING SPECIFIC INDEX:

Hi so since my example_devices worked I am trying to specifically open index one which is the what we have connected the amplifier to. 
here is the code I wrote: 
![Screenshot from 2021-08-30 16-15-08](https://user-images.githubusercontent.com/60860244/131399526-f2b05711-9243-42f2-8656-11233e3b0dd3.png)

And there is no sound output but it does full run because it outputs the "done" statement I added. Here are the warnings I get, I think perhaps there is a soundcard problem? :

![Screenshot from 2021-08-30 16-16-24](https://user-images.githubusercontent.com/60860244/131399681-69e101b6-0d8f-4ed5-a9b7-2fd15bbac320.png)

![Screenshot from 2021-08-30 16-16-29](https://user-images.githubusercontent.com/60860244/131399693-4bec8c04-3534-4585-9d76-6ffdba1569c8.png)

**Comment by zkarach1** [comment]
Here is my output from the pa_devs: 
![Screenshot from 2021-08-30 15-59-23](https://user-images.githubusercontent.com/60860244/131593601-73781105-e729-4107-984a-d2ff22f928a0.png)
![Screenshot from 2021-08-30 16-16-29](https://user-images.githubusercontent.com/60860244/131593617-ad9a5c8c-b23d-43f2-aca1-e11689824a74.png)
![Screenshot from 2021-08-30 16-15-08](https://user-images.githubusercontent.com/60860244/131593596-a6f730bc-08dd-4c5d-9b60-1844e5dbdcf1.png)

**Comment by zkarach1** [comment]
hey @gadzooks00 just wanted to check in if you were able to see my messages above! thank you

**Comment by gadzooks00** [comment]
@zkarach1 Yes, thank you for the screenshots and information. I am looking into this.

**Comment by gadzooks00** [comment]
@zkarach1 After testing out a couple of items on the syntacts side and reviewing the information you have provided, the issue seems to be on either the driver for your sound device or the sound device itself. While the system is able to identify that there is a sound device for ASLA, as per your screenshot from pa-devs, the same pa_linux_alsa.c error is being thrown. Since this is an issue upstream from Syntacts, there is not a software fix that we can include from our end. I would recommend checking to make sure the most updated stable audio drivers are being used on your system or to switch to another audio platform that your system is not having any connectivity issues with.
